
server:
  port: 8080
  
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: EXAMEN
    password: EXAMEN
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

